name: Create Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit message
        id: commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "commit_message=$COMMIT_MSG" >> $GITHUB_OUTPUT
          echo "Commit message: $COMMIT_MSG"

      - name: Check if commit message is a version number
        id: check_version
        run: |
          if [[ "${{ steps.commit.outputs.commit_message }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_version=true" >> $GITHUB_OUTPUT
            echo "Commit message is a version number"
          else
            echo "is_version=false" >> $GITHUB_OUTPUT
            echo "Commit message is not a version number"
          fi

      - name: Create tag
        if: steps.check_version.outputs.is_version == 'true'
        run: |
          git tag ${{ steps.commit.outputs.commit_message }}
          git push origin ${{ steps.commit.outputs.commit_message }}
